### ISSUE TITLE
list index out of range when running GraphBuilder.py

### ISSUE THREAD

**Issue by noncodo** [SchulzLab/Aeron#15]
Hello!
Trying to generate a custom .gfa file but hitting this snag:  
```
$ python /home/apps/Aeron/AeronScripts/GraphBuilder.py -e /home/refs/human/dna/hg38_wControl.fa -g /home/refs/human/rna/gencode.v35wControl.annotation.gtf -o aeron_out`
Reading Sequences
Done reading sequences
Reading and processing gtf
Traceback (most recent call last):
  File "/home/apps/Aeron/AeronScripts/GraphBuilder.py", line 183, in <module>
    pg = ParseGTF(fn)
  File "/home/apps/Aeron/AeronScripts/ParseGTF.py", line 36, in __init__
    en[exn[0]].append(enu[0])
IndexError: list index out of range
```
Looks like a semantic issue with the latest gencode gtf, which doesn't have double quotes next to the exon_number values. removing the double quotes on line 36 of parseGTF.py fixed it.

**Comment by ddurai** [comment]
Dear non condo,

I apologise for the late answer. Can you please post the fist few lines of your genome file and also your gtf files

I am sorry once again

regards
Dilip A Durai
