### ISSUE TITLE
.gfa missing, difficulties with graphbuilder

### ISSUE THREAD

**Issue by qiikong** [SchulzLab/Aeron#4]
We encountered some problems when trying the software as
the .gfa (input/hg38.gfa) that is provided does not seem to be valid. We
have been trying to compile a .gfa of our own using the graphbuilder.py
and gencode v33 files. Unfortunately, this does not seem to work (see
below).

 >> python GraphBuilder.py -e ../input/GRCh38.primary_assembly.genome.fa
-g ../input/hg38.gencode.v33.annotation.gtf -o gencode.hg38.gfa
Reading Sequences
Done reading sequences
Reading and processing gtf
Traceback (most recent call last):
   File "GraphBuilder.py", line 183, in <module>
     pg = ParseGTF(fn)
   File "/media/data/erst/Aeron/GraphBuilder/ParseGTF.py", line 36, in
__init__
     en[exn[0]].append(enu[0])
IndexError: list index out of range

**Comment by SchulzLab** [comment]
Dear qiikong,
we will try with the gencode gtf and try to reproduce your error.
Your remark that the hg38.gfa file is not valid, is not clear to me. What is the program call and what is the error message you obtain?

Thanks,
Marcel

**Comment by qiikong** [comment]
Dear Marcel,
The content of the file input/hg38.gfa is 3 lines
"version https://git-lfs.github.com/spec/v1
oid sha256:ff41275c90eb62d95a781ac1ebfbf3fbd51ab6aba8a4d615c37134b529f1953c
size 8305394692"
The file was cloned and as far as I can see the source is identical although a size of more than 792 MB is allocated.

Thank you,
qiikong

**Comment by SchulzLab** [comment]
Dear qiikong,
this is a problem with the large file service in GitHub. You don't have the complete file now. We are looking into the problem.
Marcel

**Comment by SchulzLab** [comment]
Hi again,
concerning the use of the Gencode gtf, this is a problem of the parser we use in graph builder as previously we only used Ensembl gtf files, there are some differences in both formats.
If you don't care at this point try to use the Ensembl transcript gtf for making the gfa file, until we have solved the issue for retrieval of the .gfa files.

Hope that helps,
Marcel

**Comment by qiikong** [comment]
Thank you very much. We will try with the ensembl files. The gencode solution was a way to circumvent the download problems from ensembl we have had. Are there any other known annotations that will work?
again thank you,
qiikong

**Comment by SchulzLab** [comment]
Hi qiikong,
I am not sure what kind of problem you had for downloads from Ensembl, but if you download the gene annotation gtf and genome fasta from here:
https://www.ensembl.org/info/data/ftp/index.html

It should work! We haven't tried other annotations, but it is important that the number of chromosomes in fasta file and gtf are both the same.
Hope that helps,
Marcel
